// Code generated by MockGen. DO NOT EDIT.
// Source: taskServiceInterface.go
//
// Generated by this command:
//
//	mockgen -source=taskServiceInterface.go -destination=task_interface_mock.go
//

// Package mock_taskHandler is a generated GoMock package.
package taskHandler

import (
	models "FinalThreeLayerUsingGOfr/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gofr "gofr.dev/pkg/gofr"
)

// MocktaskService is a mock of taskService interface.
type MocktaskService struct {
	ctrl     *gomock.Controller
	recorder *MocktaskServiceMockRecorder
	isgomock struct{}
}

// MocktaskServiceMockRecorder is the mock recorder for MocktaskService.
type MocktaskServiceMockRecorder struct {
	mock *MocktaskService
}

// NewMocktaskService creates a new mock instance.
func NewMocktaskService(ctrl *gomock.Controller) *MocktaskService {
	mock := &MocktaskService{ctrl: ctrl}
	mock.recorder = &MocktaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskService) EXPECT() *MocktaskServiceMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MocktaskService) CreateTask(ctx *gofr.Context, task models.Task) (models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task)
	ret0, _ := ret[0].(models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MocktaskServiceMockRecorder) CreateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MocktaskService)(nil).CreateTask), ctx, task)
}

// DeleteTask mocks base method.
func (m *MocktaskService) DeleteTask(ctx *gofr.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MocktaskServiceMockRecorder) DeleteTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MocktaskService)(nil).DeleteTask), ctx, id)
}

// GetAllTasks mocks base method.
func (m *MocktaskService) GetAllTasks(ctx *gofr.Context) ([]models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTasks", ctx)
	ret0, _ := ret[0].([]models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTasks indicates an expected call of GetAllTasks.
func (mr *MocktaskServiceMockRecorder) GetAllTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTasks", reflect.TypeOf((*MocktaskService)(nil).GetAllTasks), ctx)
}

// GetTaskByID mocks base method.
func (m *MocktaskService) GetTaskByID(ctx *gofr.Context, id int) (models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, id)
	ret0, _ := ret[0].(models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MocktaskServiceMockRecorder) GetTaskByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MocktaskService)(nil).GetTaskByID), ctx, id)
}

// UpdateTask mocks base method.
func (m *MocktaskService) UpdateTask(ctx *gofr.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MocktaskServiceMockRecorder) UpdateTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MocktaskService)(nil).UpdateTask), ctx, id)
}
